blank_issues_enabled: false
contact_links:
  - name: Questions and discussions
    url: https://github.com/usetheo/theo-openvoice/discussions
    about: Please use GitHub Discussions for questions and general support.
